package com.example.ui

object Localization {
    fun loc(key: String, lang: String): String {
        val map = if (lang == "it") italianMap else englishMap
        return map[key] ?: englishMap[key] ?: key
    }

    private val englishMap = mapOf(
        "app_title" to "NEON RACER",
        "top_speed" to "Top Speed",
        "handling" to "Handling",
        "base_armor" to "Base Armor",
        "equipped" to "CURRENTLY EQUIPPED",
        "equip" to "EQUIP VEHICLE",
        "unlock_for" to "UNLOCK FOR %s COINS",
        "course_subtitle" to "COURSE 08 // RETRO LANE OVERDRIVE",
        "top_down_engine" to "TOP-DOWN ENGINE",
        "high_score" to "HIGH SCORE",
        "current_drive" to "CURRENT DRIVE",
        "select_theme" to "SELECT LEVEL THEME // DYNAMIC",
        "active_theme" to "ACTIVE THEME",
        "special_obstacles_active" to "SPECIAL OBSTACLES ACTIVE",
        "start_race" to "START RETRO RACE",
        "garage_upgrades" to "GARAGE & UPGRADES",
        
        // Settings Section
        "settings_btn" to "SETTINGS",
        "settings_title" to "SYSTEM SETTINGS // GLOBAL",
        "select_language" to "SELECT INTERFACE LANGUAGE",
        "english" to "ENGLISH / EN",
        "italian" to "ITALIANO / IT",
        "active_configuration" to "ACTIVE LANGUAGE",
        "back_to_menu" to "BACK TO MAIN MENU",

        // Garage Shop
        "garage_title" to "NEON GARAGE",
        "performance_interpolators" to "PERFORMANCE INTERPOLATORS",
        "engine_tuning" to "Engine Tuning",
        "chassis_armor" to "Chassis Armor",
        "tire_traction" to "Tire Traction",
        "coin_harvester" to "Coin Harvester",
        "nitrogen_booster" to "Nitrogen Booster",
        "fast_acceleration" to "FAST ACCELERATION",
        "unlocked" to "UNLOCKED",
        "select" to "SELECT",
        "buy_for" to "BUY FOR",
        "upgrade_full" to "MAXED OUT",
        "upgrade" to "UPGRADE",
        "cost" to "COST",
        "garage_back" to "GO BACK",

        // Game Over
        "system_error" to "SYSTEM ERROR // CRITICAL IMPACT",
        "vehicle_crashed" to "VEHICLE CRASHED!",
        "run_score_stats" to "RUN SCORE STATISTICS",
        "your_run_score" to "YOUR RUN SCORE",
        "new_personal_record" to "NEW PERSONAL RECORD!",
        "coins_salvaged" to "COINS SALVAGED",
        "restart_drive" to "RESTART DRIVE",
        "drive_to_main_menu" to "DRIVE TO MAIN MENU",

        // Stage Clear
        "stage_clear_sub" to "LEVEL COMPLETE // EXCELLENT DRIVE",
        "stage_cleared" to "STAGE CLEARED!",
        "drive_analysis" to "DRIVE ANALYSIS - LEVEL %s",
        "total_run_score" to "TOTAL RUN SCORE",
        "time_taken" to "Time Taken",
        "completion_bonus" to "Completion Bonus",
        "near_miss_passes" to "Near-Miss Passes",
        "coins_acquired" to "COINS ACQUIRED",
        "drive_again" to "DRIVE AGAIN",

        // Gameplay HUD / Info
        "score" to "SCORE",
        "time" to "TIME",
        "shield" to "SHIELD",
        "speed" to "SPEED",
        "paused" to "PAUSED",
        "game_paused" to "GAME PAUSED",
        "resume" to "RESUME",
        "quit" to "QUIT",
        "lives" to "LIVES",
        "seconds" to "SEC",
        "tutorial_title" to "PILOT DOSSIER // RETRO TUTORIAL",
        "tutorial_to_take" to "COLLECT & ADVANTAGE",
        "tutorial_take_desc" to "Gold & bronze coins to level up statistics. Increases Magnet & speed efficiency!",
        "tutorial_to_avoid" to "AVOID & SURVIVE",
        "tutorial_avoid_desc" to "Enemy vehicles, roadblock barriers, oil spills, and hazards. Keeps shields intact!",
        "tutorial_skip" to "TAP TO SKIP",
        "tutorial_start_in" to "DRIVE SYNCING IN %s...",
        "gt_button_label" to "START GUIDED TUTORIAL",
        "gt_title" to "TRAINEE ACADEMY // RACER LABS",
        "gt_close" to "FINISH TUTORIAL",
        "gt_step" to "TRAINING %d / 3",
        "gt_step1_title" to "1. STEERING AND MANEUVERING",
        "gt_step1_desc" to "Tap the LEFT & RIGHT steering buttons to shift lanes. Try practicing below right now!",
        "gt_step2_title" to "2. VALUABLE PERKS & COINS",
        "gt_step2_desc" to "Collect GOLD & BRONZE coins to feed your coin harvester, power active magnets, and build huge score multipliers!",
        "gt_step3_title" to "3. DESTRUCTIVE OBSTACLES",
        "gt_step3_desc" to "Rival vehicles, roadblock barriers, and spilled oil will devastate your shields on impact. Steer clear & survive!",
        "gt_next" to "NEXT STEP",
        "gt_back" to "PREVIOUS",
        "gt_try_steering" to "TEST CONTROLS TO UNLOCK NEXT:",
        "fuel_tank" to "Gas Tank Capacity",
        "vehicle_out_of_fuel" to "OUT OF FUEL!",
        "fuel_running_low" to "LOW FUEL",
        "tutorial_fuel_title" to "REFUEL & SUSTAIN",
        "tutorial_fuel_desc" to "Collect retro fuel canisters on the road to keep your propulsion tank filled and survive!"
    )

    private val italianMap = mapOf(
        "app_title" to "NEON RACER",
        "top_speed" to "Velocità Max",
        "handling" to "Maneggevolezza",
        "base_armor" to "Blindatura",
        "equipped" to "ATTUALMENTE EQUIPAGGIATO",
        "equip" to "EQUIPAGGIA VEICOLO",
        "unlock_for" to "SBLOCCA PER %s MONETE",
        "course_subtitle" to "PERCORSO 08 // RETRO LANE OVERDRIVE",
        "top_down_engine" to "MOTORE VISTA DALL'ALTO",
        "high_score" to "MIGLIOR PUNTEGGIO",
        "current_drive" to "VEICOLO CORRENTE",
        "select_theme" to "SELEZIONA STILE TEMA // DINAMICO",
        "active_theme" to "TEMA ATTIVO",
        "special_obstacles_active" to "OSTACOLI SPECIALI ATTIVI",
        "start_race" to "AVVIA CORSA RETRÒ",
        "garage_upgrades" to "GARAGE E POTENZIAMENTI",
        
        // Settings Section
        "settings_btn" to "IMPOSTAZIONI",
        "settings_title" to "IMPOSTAZIONI DI SISTEMA // GLOBAL",
        "select_language" to "SELEZIONA LINGUA INTERFACCIA",
        "english" to "ENGLISH / EN",
        "italian" to "ITALIANO / IT",
        "active_configuration" to "LINGUA ATTIVA",
        "back_to_menu" to "TORNA AL MENU PRINCIPALE",

        // Garage Shop
        "garage_title" to "GARAGE NEON",
        "performance_interpolators" to "PARAMETRI PRESTAZIONALI",
        "engine_tuning" to "Messa a Punto Motore",
        "chassis_armor" to "Blindatura Telaio",
        "tire_traction" to "Aderenza Pneumatici",
        "coin_harvester" to "Mietitore di Monete",
        "nitrogen_booster" to "Turbo al Nitro",
        "fast_acceleration" to "ACCELERAZIONE RAPIDA",
        "unlocked" to "SBLOCCATO",
        "select" to "SELEZIONA",
        "buy_for" to "ACQUISTA PER",
        "upgrade_full" to "MASSIMO LIVELLO",
        "upgrade" to "POTENZIA",
        "cost" to "COSTO",
        "garage_back" to "INDIETRO",

        // Game Over
        "system_error" to "ERRORE DI SISTEMA // IMPATTO CRITICO",
        "vehicle_crashed" to "VEICOLO DISTRUTTO!",
        "run_score_stats" to "STATISTICHE PUNTEGGIO RUN",
        "your_run_score" to "IL TUO PUNTEGGIO",
        "new_personal_record" to "NUOVO RECORD PERSONALE!",
        "coins_salvaged" to "MONETE RECUPERATE",
        "restart_drive" to "RICOMINCIA CORSA",
        "drive_to_main_menu" to "TORNA AL MENU PRINCIPALE",

        // Stage Clear
        "stage_clear_sub" to "LIVELLO COMPLETATO // GUIDA ECCELLENTE",
        "stage_cleared" to "LIVELLO SUPERATO!",
        "drive_analysis" to "ANALISI DI GUIDA - LIVELLO %s",
        "total_run_score" to "PUNTEGGIO TOTALE RUN",
        "time_taken" to "Tempo Impiegato",
        "completion_bonus" to "Bonus Completamento",
        "near_miss_passes" to "Sorpassi Ravvicinati",
        "coins_acquired" to "MONETE ACQUISITE",
        "drive_again" to "CORRI ANCORA",

        // Gameplay HUD / Info
        "score" to "PUNTEGGIO",
        "time" to "TEMPO",
        "shield" to "SCUDO",
        "speed" to "VELOCITÀ",
        "paused" to "PAUSATO",
        "game_paused" to "GIOCO IN PAUSA",
        "resume" to "RIPRENDI",
        "quit" to "ESCI",
        "lives" to "VITE",
        "seconds" to "SEC",
        "tutorial_title" to "DOSSIER PILOTA // GUIDA RETRÒ",
        "tutorial_to_take" to "RACCOGLI & VANTAGGI",
        "tutorial_take_desc" to "Monete d'oro e bronzo per migliorare le statistiche. Aumenta efficienza di Magnete e velocità!",
        "tutorial_to_avoid" to "EVITA & SOPRAVVIVI",
        "tutorial_avoid_desc" to "Veicoli rivali, barriere stradali, chiazze d'olio e pericoli. Protegge l'integrità degli scudi!",
        "tutorial_skip" to "TOCCA PER SALTARE",
        "tutorial_start_in" to "SINCRONIZZAZIONE IMMINENTE TRA %s...",
        "gt_button_label" to "AVVIA GUIDA INTERATTIVA",
        "gt_title" to "ACCADEMIA PILOTI // LAB CORSE",
        "gt_close" to "CHIUDI CORSO",
        "gt_step" to "FASE PILOTA %d / 3",
        "gt_step1_title" to "1. CONTROLLO E STERZATA",
        "gt_step1_desc" to "Premi i pulsanti di direzione SINISTRA e DESTRA per spostare il veicolo tra le corsie. Fai pratica qui sotto!",
        "gt_step2_title" to "2. RACCOLTA BENEFIZIO E MONETE",
        "gt_step2_desc" to "Raccogli le monete d'ORO e BRONZO per potenziare le abilità, attivare i magneti e accumulare enormi moltiplicatori!",
        "gt_step3_title" to "3. OSTACOLI DESTRUTTIVI",
        "gt_step3_desc" to "Auto rivali, blocchi stradali stradali, e chiazze d'olio devasteranno i tuoi scudi all'impatto. Evitali a tutti i costi!",
        "gt_next" to "PROSSIMO PASSO",
        "gt_back" to "FASE PREC.",
        "gt_try_steering" to "PROVA I CONTROLLI PER SBLOCCARE:",
        "fuel_tank" to "Serbatoio Benzina",
        "vehicle_out_of_fuel" to "SENZA BENZINA!",
        "fuel_running_low" to "RISERVA CARB",
        "tutorial_fuel_title" to "RIFORNIMENTO & DURATA",
        "tutorial_fuel_desc" to "Raccogli le taniche di carburante sulla strada per mantenere pieno il serbatoio e continuare la corsa!"
    )
}
